import { useEffect, useState, type Dispatch, type SetStateAction } from 'react'

const messages = {
  en: {
    'nav.interface': 'INTERFACE', 'nav.protocol': 'PROTOCOL', 'nav.logs': 'LOGS', 'nav.commands': 'COMMANDS', 'nav.taskLog': 'TASK LOG', 'nav.newTask': 'NEW TASK', 'nav.dayNight': 'Switch day / night display',
    'nav.fx': 'FX', 'nav.qualityTitle': 'Cycle WebGL quality: automatic, energy saver, cinema', 'nav.qualityAuto': 'AUTO', 'nav.qualityEco': 'ECO', 'nav.qualityCinema': 'CINEMA', 'nav.modeTitle': 'Cycle core visual mode', 'nav.modeBaseline': 'MODE / BASELINE', 'nav.modeEnhanced': 'MODE / ENHANCED', 'nav.modeFeral': 'MODE / NEURAL FERAL', 'display.remote': 'REMOTE', 'display.localMock': 'LOCAL MOCK', 'display.backendManaged': 'BACKEND MANAGED', 'display.notUsed': 'NOT USED', 'display.agentPlatformApi': 'AGENT PLATFORM API', 'display.localAdapter': 'LOCAL MOCK AGENT ADAPTER',
    'dispatch.title': 'NEW AGENT TASK', 'dispatch.draft': 'DRAFT SAVES LOCALLY', 'dispatch.close': 'CLOSE', 'dispatch.loading': 'LOADING AGENT PROFILES...', 'dispatch.empty': 'NO AGENT PROFILES AVAILABLE', 'dispatch.profile': 'AGENT PROFILE', 'dispatch.input': 'PROFILE INPUT', 'dispatch.priority': 'PRIORITY', 'dispatch.approval': 'REQUIRE HUMAN APPROVAL', 'dispatch.approvalOn': 'A review gate will open before this task enters the queue.', 'dispatch.approvalOff': 'This task will enter the execution queue immediately.', 'dispatch.reset': 'RESET DRAFT', 'dispatch.confirmReset': 'CONFIRM RESET', 'dispatch.submit': 'DISPATCH TASK', 'dispatch.submitting': 'DISPATCHING...',
    'dispatch.standard': 'STANDARD', 'dispatch.standardDetail': 'Normal execution lane', 'dispatch.priorityOption': 'PRIORITY', 'dispatch.priorityDetail': 'Expedited execution lane', 'dispatch.critical': 'CRITICAL', 'dispatch.criticalDetail': 'High-signal Feral monitoring', 'dispatch.required': 'A required Profile field is missing.', 'dispatch.objectiveHint': 'Describe the bounded outcome this agent should produce.',
    'task.pause': 'PAUSE', 'task.resume': 'RESUME', 'task.cancel': 'CANCEL', 'task.retry': 'RETRY OBSERVATION TASK', 'task.close': 'CLOSE',
    'task.idle': 'AWAITING TASK', 'task.calibrating': 'CALIBRATING CORE', 'task.routing': 'ROUTING CONTEXT', 'task.executing': 'EXECUTING TOOLS', 'task.synthesizing': 'SYNTHESIZING RESULT', 'task.complete': 'TASK COMPLETE', 'task.paused': 'TASK PAUSED', 'task.failed': 'TASK FAILED', 'task.cancelled': 'TASK CANCELLED', 'state.idle': 'STANDBY', 'state.queued': 'QUEUED', 'state.running': 'COGNIZANT', 'state.paused': 'SUSPENDED', 'state.waitingApproval': 'AWAITING APPROVAL', 'state.complete': 'RESULT READY', 'state.failed': 'MISSION FAILED', 'state.cancelled': 'MISSION HALTED',
    'scenario.loading': 'LOADING...', 'scenario.active': 'STATE ACTIVE', 'scenario.select': 'SELECT A STATE TO BEGIN ACCEPTANCE', 'scenario.queued': 'QUEUED', 'scenario.queuedDetail': 'Queue visibility and priority controls', 'scenario.running': 'RUNNING', 'scenario.runningDetail': 'Live agent telemetry and task stream', 'scenario.paused': 'PAUSED', 'scenario.pausedDetail': 'Resume and cancel control state', 'scenario.waitingApproval': 'APPROVAL', 'scenario.waitingApprovalDetail': 'Human approval waiting state', 'scenario.completed': 'COMPLETE', 'scenario.completedDetail': 'Result review and history state', 'scenario.failed': 'FAILED', 'scenario.failedDetail': 'Failure recovery and retry state', 'scenario.cancelled': 'CANCELLED', 'scenario.cancelledDetail': 'Operator stop and retry state',
    'queue.title': 'MISSION QUEUE', 'queue.close': 'CLOSE', 'queue.subtitle': 'Approved tasks run in this order after the active mission resolves.', 'queue.hold': 'HOLD AUTO-DISPATCH', 'queue.resume': 'RESUME AUTO-DISPATCH', 'queue.empty': 'No queued missions.', 'queue.emptyDetail': 'New approved requests will wait here while an agent is active.',
    'confirm.heading': 'OPERATOR CONFIRMATION', 'confirm.kicker': 'DESTRUCTIVE RUNTIME REQUEST', 'confirm.cancelTitle': 'Cancel active mission?', 'confirm.cancelMessage': 'The runtime will stop the current task. Completed stages remain in the mission archive.', 'confirm.removeTitle': 'Remove queued mission?', 'confirm.removeMessage': 'will be removed before launch.', 'confirm.cancelAction': 'CONFIRM CANCEL', 'confirm.removeAction': 'REMOVE FROM QUEUE', 'confirm.keep': 'KEEP TASK', 'confirm.requesting': 'REQUESTING', 'confirm.error': 'REQUEST FAILED. RETRY WHEN READY.',
    'runtime.restoring': 'RESTORING AGENT LINK', 'runtime.offline': 'AGENT LINK OFFLINE', 'runtime.interrupted': 'AGENT LINK INTERRUPTED', 'runtime.refreshing': 'Refreshing task and Profile snapshots from the active adapter.', 'runtime.waiting': 'WAITING FOR NETWORK', 'runtime.retry': 'RETRY CONNECTION', 'scene.core': 'Animated three dimensional sentient core', 'scene.loading': 'INITIALIZING NEURAL RUNTIME', 'scene.recovering': 'NEURAL RUNTIME RECOVERING', 'queue.moveUp': 'Move task up', 'queue.moveDown': 'Move task down', 'queue.remove': 'Remove task from queue', 'runtime.timeout': 'AGENT REQUEST TIMED OUT', 'runtime.timeoutDetail': 'The Agent runtime did not respond in time. The last valid snapshot is still available.', 'runtime.network': 'AGENT NETWORK UNAVAILABLE', 'runtime.networkDetail': 'The Agent runtime could not be reached. Check the connection and retry when ready.', 'runtime.permission': 'AGENT ACCESS DENIED', 'runtime.permissionDetail': 'Your current credentials cannot perform this runtime operation.', 'runtime.taskFailed': 'AGENT TASK FAILED', 'runtime.taskFailedDetail': 'The mission returned a failure state. Review the task trace before retrying.', 'runtime.unavailableDetail': 'The Agent runtime is temporarily unavailable. The last valid snapshot remains visible.', 'runtime.offlineDetail': 'The browser is offline. The last valid task snapshot remains available.', 'runtime.dismiss': 'Dismiss runtime status',
    'status.session': 'SESSION', 'status.taskTime': 'TASK TIME', 'status.queue': 'QUEUE', 'status.ready': 'READY', 'status.hold': 'HOLD', 'status.link': 'LINK', 'status.approvalHold': 'APPROVAL HOLD', 'status.queueHold': 'QUEUE HOLD',
    'workspace.title': 'WORKSPACE', 'workspace.local': 'LOCAL MOCK ENVIRONMENT', 'workspace.remote': 'REMOTE AGENT ENVIRONMENT', 'workspace.close': 'CLOSE', 'workspace.overview': 'OPERATIONAL OVERVIEW', 'workspace.intake': 'READY FOR INTAKE', 'workspace.active': 'ACTIVE MISSION', 'workspace.waiting': 'WAITING QUEUE', 'workspace.ledger': 'MISSION LEDGER', 'workspace.openLog': 'OPEN TASK LOG', 'workspace.manageQueue': 'MANAGE QUEUE', 'workspace.openHistory': 'OPEN HISTORY', 'workspace.create': 'CREATE AGENT TASK',
    'workspace.none': 'NONE', 'workspace.noProfile': 'NO PROFILE SELECTED', 'workspace.held': 'AUTO-DISPATCH HELD', 'workspace.autoReady': 'AUTO-DISPATCH READY', 'workspace.sessionHistory': 'SESSION-SCOPED HISTORY', 'workspace.protocol': 'EXECUTION PROTOCOL', 'workspace.protocolTitle': 'Connector registry', 'workspace.scenario': 'SCENARIO LAB', 'workspace.acceptance': 'LOCAL UI ACCEPTANCE ONLY', 'workspace.loadScenario': 'Load a deterministic interface state without contacting a business service.',
    'workspace.protocolCopy': 'These entries describe the local front-end contract. They are not live business integrations.', 'workspace.adapter': 'ACTIVE ADAPTER', 'workspace.transport': 'TRANSPORT', 'workspace.speed': 'PLAN SPEED', 'workspace.externalData': 'EXTERNAL DATA', 'workspace.gatewayCopy': 'Dispatch, state transitions, queue and ledger', 'workspace.approvalGate': 'HUMAN APPROVAL GATE', 'workspace.approvalCopy': 'Operator approval before launch', 'workspace.connectors': 'BUSINESS CONNECTORS', 'workspace.connectorCopy': 'CRM, tickets, knowledge and warehouse', 'workspace.notConnected': 'NOT CONNECTED', 'workspace.remoteNote': 'Contract v1 is connected through the configured HTTP and SSE adapters. Credentials remain outside UI state.', 'workspace.localNote': 'Configure VITE_AGENT_TRANSPORT and VITE_AGENT_BASE_URL to connect the Contract v1 backend.', 'workspace.currentState': 'CURRENT STATE', 'workspace.source': 'SOURCE', 'workspace.audit': 'OPERATOR AUDIT / GATEWAY LEDGER', 'workspace.telemetry': 'RUNTIME TELEMETRY / ORDERED AGENT EVENTS', 'workspace.noAudit': 'No operator audit records yet.', 'workspace.noEvents': 'No task events in this session.', 'workspace.noEventsDetail': 'Dispatch a mission to populate the runtime stream.', 'workspace.logsNote': 'The active Gateway owns task events and operator audit records. A production adapter can persist this ledger in a tamper-resistant backend.',
    'timeline.title': 'MISSION TRACE', 'timeline.close': 'CLOSE', 'timeline.idle': 'Awaiting a dispatched agent task.', 'timeline.cancelled': 'Mission stopped by operator. No further actions will run.', 'timeline.failed': 'Mission interrupted. Review the task stream before retrying.',
    'timeline.parse': 'INTENT PARSE', 'timeline.route': 'ROUTE PLAN', 'timeline.execute': 'LIVE EXECUTION', 'timeline.synthesis': 'SYNTHESIS', 'timeline.complete': 'MISSION COMPLETE', 'timeline.parseDetail': 'Parsing task intent', 'timeline.routeDetail': 'Selecting agent tools', 'timeline.executeDetail': 'Running delegated workflow', 'timeline.synthesisDetail': 'Compiling operator result', 'timeline.completeDetail': 'Result ready for review', 'timeline.checkpoint': 'Checkpoint held by operator', 'timeline.verified': 'Verified', 'timeline.queued': 'Queued',
    'result.ready': 'RESULT READY', 'result.verified': 'VERIFIED', 'result.close': 'CLOSE', 'result.requesting': 'REQUESTING', 'result.requested': 'REQUESTED', 'result.retry': 'RETRY ACTION', 'result.export': 'EXPORT .TXT',
    'result.packet': 'RESULT PACKET', 'result.fileTitle': 'MCP-2099 / AGENT MISSION RESULT', 'result.fileStatus': 'STATUS: READY FOR REVIEW',
    'history.title': 'MISSION HISTORY', 'history.close': 'CLOSE', 'history.subtitle': 'Resolved missions returned by the active Agent Gateway.', 'history.search': 'Search task history', 'history.all': 'ALL', 'history.complete': 'COMPLETE', 'history.cancelled': 'CANCELLED', 'history.failed': 'FAILED', 'history.empty': 'No resolved missions yet.', 'history.emptyDetail': 'Dispatch a task to begin the local ledger.', 'history.noMatch': 'No local history matches this filter.', 'history.review': 'ARCHIVE REVIEW', 'history.export': 'EXPORT ARCHIVE',
    'panels.trigger': 'PANELS', 'panels.title': 'PANEL INDEX', 'panels.close': 'CLOSE', 'panels.trace': 'MISSION TRACE', 'panels.result': 'RESULT REVIEW', 'panels.history': 'MISSION HISTORY', 'panels.queue': 'MISSION QUEUE', 'panels.open': 'OPEN', 'panels.restore': 'RESTORE', 'panels.wait': 'WAIT', 'panels.waiting': 'WAITING', 'panels.resultUnavailable': 'Result review becomes available when the mission is complete', 'panels.hideResult': 'Hide result review', 'panels.openResult': 'Open result review',
    'left.kicker': 'COGNITIVE ARCHITECTURE / 09', 'left.description': 'Primary neural cluster visualizing real-time thought processing and decision tree branching.', 'left.state': 'State:', 'left.approval': 'AWAITING APPROVAL', 'left.queue': 'QUEUE',
    'metrics.title': 'NEURAL TELEMETRY', 'metrics.load': 'PROCESSING LOAD', 'metrics.firing': 'SYNAPTIC FIRING RATE', 'metrics.thoughts': 'ACTIVE THOUGHTS',
    'command.search': 'Search control commands', 'command.empty': 'No matching control command.', 'command.close': 'CLOSE', 'command.execute': 'EXECUTE',
    'command.create': 'Create agent task', 'command.createDetail': 'Choose a business profile and dispatch objective', 'command.interface': 'Open interface workspace', 'command.interfaceDetail': 'Review active mission, queue and local history', 'command.protocol': 'Open protocol registry', 'command.protocolDetail': 'Inspect local mock connectors and integration boundary', 'command.audit': 'Open audit logs', 'command.auditDetail': 'Inspect operator actions and runtime telemetry', 'command.queue': 'Manage mission queue', 'command.queueDetail': 'Inspect waiting tasks and automatic dispatch state', 'command.history': 'Open mission history', 'command.historyDetail': 'Review persisted local mission archives', 'command.visual': 'Cycle visual mode', 'command.quality': 'Cycle scene quality', 'command.taskLog': 'Toggle task log', 'command.taskLogDetail': 'Inspect the active agent task stream', 'command.theme': 'Cycle display theme', 'command.reset': 'Reset visual baseline', 'command.resetDetail': 'Return the core to its baseline profile',
    'approval.heading': 'HUMAN APPROVAL GATE', 'approval.kicker': 'AGENT LAUNCH REQUIRES OPERATOR CONSENT', 'approval.title': 'Review mission before execution.', 'approval.profile': 'PROFILE', 'approval.priority': 'PRIORITY', 'approval.objective': 'OBJECTIVE', 'approval.decline': 'DECLINE', 'approval.approve': 'APPROVE & LAUNCH',
  },
  'zh-CN': {
    'nav.interface': '界面', 'nav.protocol': '协议', 'nav.logs': '日志', 'nav.commands': '命令', 'nav.taskLog': '任务日志', 'nav.newTask': '新建任务', 'nav.dayNight': '切换昼夜显示',
    'nav.fx': '特效', 'nav.qualityTitle': '切换 WebGL 质量：自动、节能、影院', 'nav.qualityAuto': '自动', 'nav.qualityEco': '节能', 'nav.qualityCinema': '影院', 'nav.modeTitle': '切换核心视觉模式', 'nav.modeBaseline': '模式 / 基线', 'nav.modeEnhanced': '模式 / 增强', 'nav.modeFeral': '模式 / 神经狂暴', 'display.remote': '远程', 'display.localMock': '本地模拟', 'display.backendManaged': '后端管理', 'display.notUsed': '未使用', 'display.agentPlatformApi': '智能体平台接口', 'display.localAdapter': '本地模拟智能体适配器',
    'dispatch.title': '新建智能体任务', 'dispatch.draft': '草稿仅保存在本地', 'dispatch.close': '关闭', 'dispatch.loading': '正在加载智能体配置...', 'dispatch.empty': '暂无可用智能体配置', 'dispatch.profile': '智能体配置', 'dispatch.input': '配置输入', 'dispatch.priority': '优先级', 'dispatch.approval': '需要人工审批', 'dispatch.approvalOn': '任务进入队列前将打开审批确认。', 'dispatch.approvalOff': '任务将立即进入执行队列。', 'dispatch.reset': '重置草稿', 'dispatch.confirmReset': '确认重置', 'dispatch.submit': '下发任务', 'dispatch.submitting': '正在下发...',
    'dispatch.standard': '标准', 'dispatch.standardDetail': '常规执行通道', 'dispatch.priorityOption': '优先', 'dispatch.priorityDetail': '加速执行通道', 'dispatch.critical': '关键', 'dispatch.criticalDetail': '高信号狂暴监控', 'dispatch.required': '缺少必填的配置字段。', 'dispatch.objectiveHint': '描述该智能体需要产出的明确结果。',
    'task.pause': '暂停', 'task.resume': '继续执行', 'task.cancel': '取消任务', 'task.retry': '重新发起观察任务', 'task.close': '关闭',
    'task.idle': '等待任务', 'task.calibrating': '正在校准核心', 'task.routing': '正在路由上下文', 'task.executing': '正在执行工具', 'task.synthesizing': '正在整理结果', 'task.complete': '任务完成', 'task.paused': '任务已暂停', 'task.failed': '任务失败', 'task.cancelled': '任务已取消', 'state.idle': '待命', 'state.queued': '已排队', 'state.running': '运行中', 'state.paused': '已暂停', 'state.waitingApproval': '等待审批', 'state.complete': '结果已就绪', 'state.failed': '任务失败', 'state.cancelled': '任务已终止',
    'scenario.loading': '正在加载...', 'scenario.active': '状态已激活', 'scenario.select': '选择状态开始验收', 'scenario.queued': '已排队', 'scenario.queuedDetail': '查看队列和优先级控制', 'scenario.running': '运行中', 'scenario.runningDetail': '查看实时智能体遥测和任务流', 'scenario.paused': '已暂停', 'scenario.pausedDetail': '查看继续和取消控制状态', 'scenario.waitingApproval': '等待审批', 'scenario.waitingApprovalDetail': '查看人工审批等待状态', 'scenario.completed': '已完成', 'scenario.completedDetail': '查看结果和历史记录状态', 'scenario.failed': '失败', 'scenario.failedDetail': '查看失败恢复和重试状态', 'scenario.cancelled': '已取消', 'scenario.cancelledDetail': '查看操作员停止和重试状态',
    'queue.title': '任务队列', 'queue.close': '关闭', 'queue.subtitle': '当前任务结束后，已批准任务将按此顺序执行。', 'queue.hold': '暂停自动下发', 'queue.resume': '恢复自动下发', 'queue.empty': '暂无排队任务。', 'queue.emptyDetail': '智能体执行期间，新批准的请求会在此等待。',
    'confirm.heading': '操作确认', 'confirm.kicker': '破坏性运行时请求', 'confirm.cancelTitle': '取消当前任务？', 'confirm.cancelMessage': '运行时将停止当前任务，已完成阶段仍会保留在任务归档中。', 'confirm.removeTitle': '移除排队任务？', 'confirm.removeMessage': '将在启动前从队列中移除。', 'confirm.cancelAction': '确认取消', 'confirm.removeAction': '移除队列任务', 'confirm.keep': '保留任务', 'confirm.requesting': '正在请求', 'confirm.error': '请求失败，请准备后重试。',
    'runtime.restoring': '正在恢复智能体连接', 'runtime.offline': '智能体连接离线', 'runtime.interrupted': '智能体连接中断', 'runtime.refreshing': '正在从当前适配器刷新任务和配置快照。', 'runtime.waiting': '等待网络恢复', 'runtime.retry': '重试连接', 'scene.core': '动态三维感知核心', 'scene.loading': '正在初始化神经运行时', 'scene.recovering': '正在恢复神经运行时', 'queue.moveUp': '上移任务', 'queue.moveDown': '下移任务', 'queue.remove': '从队列移除任务', 'runtime.timeout': '智能体请求超时', 'runtime.timeoutDetail': '智能体运行时未在限定时间内响应，最近一次有效快照仍然可用。', 'runtime.network': '智能体网络不可用', 'runtime.networkDetail': '无法连接智能体运行时，请检查连接后重试。', 'runtime.permission': '智能体访问被拒绝', 'runtime.permissionDetail': '当前凭据无权执行此运行时操作。', 'runtime.taskFailed': '智能体任务失败', 'runtime.taskFailedDetail': '任务返回失败状态，请在重试前检查任务轨迹。', 'runtime.unavailableDetail': '智能体运行时暂时不可用，最近一次有效快照仍保持可见。', 'runtime.offlineDetail': '浏览器当前离线，最近一次有效任务快照仍然可用。', 'runtime.dismiss': '关闭运行时状态提示',
    'status.session': '会话', 'status.taskTime': '任务耗时', 'status.queue': '队列', 'status.ready': '就绪', 'status.hold': '暂停', 'status.link': '连接', 'status.approvalHold': '等待审批', 'status.queueHold': '队列暂停',
    'workspace.title': '工作台', 'workspace.local': '本地模拟环境', 'workspace.remote': '远程智能体环境', 'workspace.close': '关闭', 'workspace.overview': '运行概览', 'workspace.intake': '等待接收任务', 'workspace.active': '当前任务', 'workspace.waiting': '等待队列', 'workspace.ledger': '任务账本', 'workspace.openLog': '打开任务日志', 'workspace.manageQueue': '管理队列', 'workspace.openHistory': '打开历史记录', 'workspace.create': '创建智能体任务',
    'workspace.none': '无', 'workspace.noProfile': '未选择配置', 'workspace.held': '自动下发已暂停', 'workspace.autoReady': '自动下发就绪', 'workspace.sessionHistory': '当前会话历史', 'workspace.protocol': '执行协议', 'workspace.protocolTitle': '连接器注册表', 'workspace.scenario': '场景实验室', 'workspace.acceptance': '仅限本地界面验收', 'workspace.loadScenario': '加载确定性的界面状态，不会访问业务服务。',
    'workspace.protocolCopy': '这些条目描述本地前端契约，不代表已接入的真实业务集成。', 'workspace.adapter': '当前适配器', 'workspace.transport': '传输方式', 'workspace.speed': '计划速度', 'workspace.externalData': '外部数据', 'workspace.gatewayCopy': '任务下发、状态流转、队列和账本', 'workspace.approvalGate': '人工审批确认', 'workspace.approvalCopy': '启动前由操作员审批', 'workspace.connectors': '业务连接器', 'workspace.connectorCopy': 'CRM、工单、知识库和仓储', 'workspace.notConnected': '未连接', 'workspace.remoteNote': 'Contract v1 通过已配置的 HTTP 和 SSE 适配器连接，凭据不保存在界面状态中。', 'workspace.localNote': '配置 VITE_AGENT_TRANSPORT 和 VITE_AGENT_BASE_URL 后可连接 Contract v1 后端。', 'workspace.currentState': '当前状态', 'workspace.source': '来源', 'workspace.audit': '操作审计 / 网关账本', 'workspace.telemetry': '运行时遥测 / 有序智能体事件', 'workspace.noAudit': '暂无操作审计记录。', 'workspace.noEvents': '当前会话没有任务事件。', 'workspace.noEventsDetail': '下发任务后将填充运行时事件流。', 'workspace.logsNote': '当前网关负责任务事件和操作审计记录，生产适配器可将此账本持久化到防篡改后端。',
    'timeline.title': '任务轨迹', 'timeline.close': '关闭', 'timeline.idle': '等待已下发的智能体任务。', 'timeline.cancelled': '任务已由操作员停止，后续操作不会继续执行。', 'timeline.failed': '任务已中断，请在重试前查看任务流。',
    'timeline.parse': '意图解析', 'timeline.route': '路由计划', 'timeline.execute': '实时执行', 'timeline.synthesis': '结果综合', 'timeline.complete': '任务完成', 'timeline.parseDetail': '正在解析任务意图', 'timeline.routeDetail': '正在选择智能体工具', 'timeline.executeDetail': '正在运行委派工作流', 'timeline.synthesisDetail': '正在整理操作结果', 'timeline.completeDetail': '结果已准备好供查看', 'timeline.checkpoint': '操作员暂停的检查点', 'timeline.verified': '已验证', 'timeline.queued': '已排队',
    'result.ready': '结果已就绪', 'result.verified': '已验证', 'result.close': '关闭', 'result.requesting': '正在请求', 'result.requested': '已提交', 'result.retry': '重试操作', 'result.export': '导出 .TXT',
    'result.packet': '结果包', 'result.fileTitle': 'MCP-2099 / 智能体任务结果', 'result.fileStatus': '状态：等待查看',
    'history.title': '任务历史', 'history.close': '关闭', 'history.subtitle': '由当前智能体网关返回的已结束任务。', 'history.search': '搜索任务历史', 'history.all': '全部', 'history.complete': '已完成', 'history.cancelled': '已取消', 'history.failed': '失败', 'history.empty': '暂无已结束任务。', 'history.emptyDetail': '下发任务后将在本地账本中记录。', 'history.noMatch': '没有符合该筛选条件的本地历史。', 'history.review': '归档查看', 'history.export': '导出归档',
    'panels.trigger': '面板', 'panels.title': '面板索引', 'panels.close': '关闭', 'panels.trace': '任务轨迹', 'panels.result': '结果查看', 'panels.history': '任务历史', 'panels.queue': '任务队列', 'panels.open': '已打开', 'panels.restore': '恢复显示', 'panels.wait': '等待', 'panels.waiting': '等待中', 'panels.resultUnavailable': '任务完成后可查看结果', 'panels.hideResult': '隐藏结果查看', 'panels.openResult': '打开结果查看',
    'left.kicker': '认知架构 / 09', 'left.description': '主神经集群实时呈现思维处理与决策树分支。', 'left.state': '状态：', 'left.approval': '等待审批', 'left.queue': '队列',
    'metrics.title': '神经遥测', 'metrics.load': '处理负载', 'metrics.firing': '突触激发速率', 'metrics.thoughts': '活跃思维',
    'command.search': '搜索控制命令', 'command.empty': '没有匹配的控制命令。', 'command.close': '关闭', 'command.execute': '执行',
    'command.create': '创建智能体任务', 'command.createDetail': '选择业务配置并下发任务目标', 'command.interface': '打开界面工作台', 'command.interfaceDetail': '查看当前任务、队列和本地历史', 'command.protocol': '打开协议注册表', 'command.protocolDetail': '查看本地模拟连接器和集成边界', 'command.audit': '打开审计日志', 'command.auditDetail': '查看操作员动作和运行时遥测', 'command.queue': '管理任务队列', 'command.queueDetail': '查看等待任务和自动下发状态', 'command.history': '打开任务历史', 'command.historyDetail': '查看本地持久化的任务归档', 'command.visual': '切换视觉模式', 'command.quality': '切换渲染质量', 'command.taskLog': '切换任务日志', 'command.taskLogDetail': '查看当前智能体任务流', 'command.theme': '切换显示主题', 'command.reset': '重置视觉基线', 'command.resetDetail': '将核心恢复为基线视觉配置',
    'approval.heading': '人工审批确认', 'approval.kicker': '启动智能体需要操作员同意', 'approval.title': '请在执行前检查任务。', 'approval.profile': '配置', 'approval.priority': '优先级', 'approval.objective': '目标', 'approval.decline': '拒绝', 'approval.approve': '批准并启动',
  },
} as const

export type Locale = keyof typeof messages
export type TranslationKey = keyof typeof messages.en
export interface LocaleState { locale: Locale; setLocale: Dispatch<SetStateAction<Locale>> }
export const isLocale = (value: unknown): value is Locale => value === 'en' || value === 'zh-CN'
export const translate = (locale: Locale, key: TranslationKey) => messages[locale][key]

export function useLocaleState(): LocaleState {
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === 'undefined') return 'en'
    const stored = window.localStorage.getItem('mcp2099.locale')
    return isLocale(stored) ? stored : 'en'
  })
  useEffect(() => { window.localStorage.setItem('mcp2099.locale', locale) }, [locale])
  return { locale, setLocale }
}
